<?php
/**
 * @file
 * Code for the Disasters feature.
 */

include_once 'hr_disasters.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_disasters_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_disasters';
  $feature->name = t('Disasters');
  $feature->description = t('Activate if your operation has multiple disasters.');
  $feature->components = array(
    'node' => array(
      'hr_disaster',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

